#+TITLE: Doom Emacs literate config
 #+options: \n:t

* My info
#+begin_src elisp
(setq user-full-name "Arsalan Kazmi"
      user-mail-address "sonicspeed848@gmail.com")
#+end_src
* Appearance
** Font
Set the monospace and variable fonts.
#+begin_src elisp
(setq doom-font (font-spec :family "Cascadia Code" :size 14)
      doom-variable-pitch-font (font-spec :family "sans" :size 15))
#+end_src
** Theme
Set the theme. Obviously.
#+begin_src elisp
(setq doom-theme 'doom-dracula)
#+end_src
** Line numbers
Use normal line numbers. Relative confuses me.
#+begin_src elisp
(setq display-line-numbers-type t)
#+end_src
** Indentation
GNU style indentation just feels off to me.
#+begin_src elisp
(setq c-default-style "linux"
      c-basic-offset 4)
(setq tab-width 4)
#+end_src
** Clock
Display a clock in the modeline.
#+begin_src elisp
(display-time-mode t)
#+end_src
* Org
** Directory
Agenda stuff will go here, I guess.
#+begin_src elisp
(setq org-directory "~/org/")
#+end_src
** Emphasis markers
This hides emphasis markers like =*bold*=, =/italic/= and =_underline_= and only shows them when the cursor hovers over them.
#+begin_src elisp
(setq org-hide-emphasis-markers t)
(add-hook 'org-mode-hook 'org-appear-mode)
#+end_src
** Heading font size and other formatting
Increase the font for headings, title and info, change ellipsis to downward triangle, and hide the title, date, author, subtitle and email keywords.
#+begin_src elisp
(defun org-heading-plus-size ()
  "Sets font sizes for Org headings, title and info."
  (set-face-attribute 'org-level-3 nil :height 1.2)
  (set-face-attribute 'org-level-2 nil :height 1.3)
  (set-face-attribute 'org-level-1 nil :height 1.5)
  (set-face-attribute 'org-document-title nil :height 1.7)
  (set-face-attribute 'org-document-info nil :height 1.2)
  (setq-default org-hidden-keywords '(title date author subtitle email))
  (setq-default org-ellipsis '" ▼ "))
(add-hook 'org-mode-hook 'org-heading-plus-size)
#+end_src
* Key bindings
** Funny quit command
This command requires the user to type =<SPC>cya= to quit Emacs.
As in, press the =Space= key, then type "cya", as if you're saying "cya" or "see you" to Emacs.
#+begin_src elisp
(map! :leader
      :desc "Quit Doom in a funny way"
      "c y a" #'save-buffers-kill-terminal)
#+end_src
** dmenu
This is just for when I use EXWM.
#+begin_src elisp
(map! :leader
      :desc "dmenu"
      "d" #'dmenu)
#+end_src
** Tab switching
This allows for easy tab switching with [[https://github.com/ema2159/centaur-tabs][Centaur Tabs]].
#+begin_src elisp
(map! :leader
      :desc "Left tab"
      "[" #'centaur-tabs-backward-tab)
(map! :leader
      :desc "Right tab"
      "]" #'centaur-tabs-forward-tab)
#+end_src
** i3wm-inspired
#+begin_src elisp
(map! "s-d" #'dmenu
      "<s-return>" #'+vterm/toggle
      "s-h" #'evil-window-left
      "s-j" #'evil-window-down
      "s-k" #'evil-window-up
      "s-l" #'evil-window-right
      "s-H" #'evil-window-move-left
      "s-J" #'evil-window-move-down
      "s-K" #'evil-window-move-up
      "s-L" #'evil-window-move-right)
#+end_src
* EXWM
When EXWM is loaded, a shell script is executed to set stuff like a compositor and a background.
#+begin_src elisp
(setq-default exwm-replace 'nil)
(defun exwm-custom-init-stuff ()
  "Runs stuff when EXWM starts."
  (call-process "/bin/bash" "~/.doom.d/exwm-init-script.sh")
  (message "EXWM custom init stuff loaded!"))
(add-hook 'exwm-init-hook 'exwm-custom-init-stuff)
(require 'exwm)
(exwm-enable)
#+end_src
